// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA99sZErXbuioFUN99H5aog6XMn_EZXMbE',
    appId: '1:442085718339:web:74ce6a137022053d5997f6',
    messagingSenderId: '442085718339',
    projectId: 'flutter-firebase-project-d137f',
    authDomain: 'flutter-firebase-project-d137f.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-d137f.appspot.com',
    measurementId: 'G-81WHTWSH5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWmSwxUvH_-vHwEeGE8y_pokhVC4fE-Kg',
    appId: '1:442085718339:android:7ce7bfcea2a6083d5997f6',
    messagingSenderId: '442085718339',
    projectId: 'flutter-firebase-project-d137f',
    storageBucket: 'flutter-firebase-project-d137f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWePI1gfWA5ieGdw58ulJgQjAattS-enE',
    appId: '1:442085718339:ios:42ed1bf7b677ec855997f6',
    messagingSenderId: '442085718339',
    projectId: 'flutter-firebase-project-d137f',
    storageBucket: 'flutter-firebase-project-d137f.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWePI1gfWA5ieGdw58ulJgQjAattS-enE',
    appId: '1:442085718339:ios:42ed1bf7b677ec855997f6',
    messagingSenderId: '442085718339',
    projectId: 'flutter-firebase-project-d137f',
    storageBucket: 'flutter-firebase-project-d137f.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA99sZErXbuioFUN99H5aog6XMn_EZXMbE',
    appId: '1:442085718339:web:d2e6c36d468082805997f6',
    messagingSenderId: '442085718339',
    projectId: 'flutter-firebase-project-d137f',
    authDomain: 'flutter-firebase-project-d137f.firebaseapp.com',
    storageBucket: 'flutter-firebase-project-d137f.appspot.com',
    measurementId: 'G-2809EWBE3J',
  );
}
